import ConvexClientProvider from "@/components/ConvexClientProvider";
import {
  ClerkProvider
} from '@clerk/nextjs';
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* these two clerk and convex provider component are high order component that will facilitate both clerk and convex to all the other components that will be requiring it, so we encapsulate it with these higher order components and as such the {children} i.e it'll be able to use clerk and then with the convex it'll be able to use both while convex uses clerk */}
        <ClerkProvider
          signInFallbackRedirectUrl='/dashboard'
          signUpFallbackRedirectUrl='/dashboard'
        >
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
